using System;
using System.Collections.Generic;

using Broiler.CSS;

namespace Broiler.Layout.Engine;

/// <summary>
/// Where the content before a float among a block's inline content left it in the block's last
/// line layout: the line that content reached, the line's top then, and how much of the line's
/// width the content takes.
/// </summary>
/// <remarks>
/// The top is the line's when the flow reached the float: what comes after the float on the line
/// can move the line further down, below floats it does not fit beside, the float itself among
/// them, while the float stays where the line was.
/// </remarks>
internal readonly record struct InlineFloatPlacement(CssLineBox Line, double LineTop, double ContentWidth);

/// <summary>
/// The floats among a block's inline content, and the line each is placed on (CSS 2.1 §9.5.1).
/// </summary>
/// <remarks>
/// <para>
/// A float is out of the flow, but it is placed where the flow reached: rule 7 of §9.5.1 keeps its
/// top from rising above "the top of any line-box containing a box generated by an element earlier
/// in the source document". Browsers place it at the top of the line the content before it is on
/// when it fits in the room that line has left, and below the line when it does not.
/// </para>
/// <para>
/// A block lays its inline content out without its floats, since where each float goes depends on
/// that content, then places the floats and lays the lines out again beside them. The floats were
/// placed at the top of the block whatever line their content had reached, and the lines above
/// them were shortened beside them; and a float inside an inline box was never placed at all.
/// </para>
/// </remarks>
internal static class InlineFloats
{
    /// <summary>
    /// The floats among <paramref name="blockBox"/>'s inline content, in document order: its
    /// floated children, and the floats inside the inline boxes it holds, which are placed in its
    /// lines as a float beside them is.
    /// </summary>
    /// <remarks>
    /// A flex or grid container's children are its items, not inline content: its floated
    /// children are taken, as before, and nothing inside them.
    /// </remarks>
    internal static List<CssBox> Of(CssBox blockBox)
    {
        var floats = new List<CssBox>();
        Collect(blockBox, floats, descend: !IsFlexOrGridContainer(blockBox));
        return floats;
    }

    private static void Collect(CssBox box, List<CssBox> floats, bool descend)
    {
        foreach (var child in box.Boxes)
        {
            if (child.Display == CssConstants.None)
                continue;

            if (child.Float != CssConstants.None)
            {
                floats.Add(child);
                continue;
            }

            if (descend && IsInlineBox(child))
                Collect(child, floats, descend);
        }
    }

    /// <summary>
    /// Whether <paramref name="box"/> is an inline box whose content is laid out in its block's
    /// lines: not an atomic inline, which lays its own out, nor one taken out of the flow.
    /// </summary>
    private static bool IsInlineBox(CssBox box) =>
        box.Display == CssConstants.Inline
        && box.Position is not (CssConstants.Absolute or CssConstants.Fixed);

    internal static bool IsFlexOrGridContainer(CssBox box) =>
        box.Display is "flex" or "inline-flex" or "grid" or "inline-grid";

    /// <summary>
    /// The highest <paramref name="floatBox"/>'s margin box may be placed: the top of the line the
    /// content before it reached, when the float fits in the room that line has left beside the
    /// floats before it, or the line's bottom when it does not. Null when the float was not placed
    /// among inline content in its block's current lines.
    /// </summary>
    internal static double? TopFloor(CssBox floatBox, IReadOnlyList<CssBox> precedingFloats, double contentLeft, double contentRight)
    {
        if (floatBox.InlineFloatPlacement is not { } placement)
            return null;

        double lineTop = placement.LineTop + placement.Line.RestackTop;

        var owner = placement.Line.OwnerBox;

        if (!IsInInlineContentOf(floatBox, owner) || !owner.LineBoxes.Contains(placement.Line))
            return null;

        if (placement.ContentWidth <= 0)
            return lineTop;

        double lineBottom = Math.Max(lineTop, placement.Line.FlowBottom is double flowBottom
            ? flowBottom + placement.Line.RestackBottom
            : lineTop);
        double height = lineBottom - lineTop;
        var bands = LineFloatBands.Of(precedingFloats);
        double room = bands.RightAt(lineTop, height, contentRight) - bands.LeftAt(lineTop, height, contentLeft);
        double width = floatBox.Size.Width + floatBox.ActualMarginLeft + floatBox.ActualMarginRight;

        return placement.ContentWidth + width <= room + 0.01 ? lineTop : lineBottom;
    }

    /// <summary>
    /// The highest <paramref name="floatBox"/> may be placed from where the content before it left
    /// it in its block's current lines, beside the floats before it, as <see cref="TopFloor(CssBox,
    /// IReadOnlyList{CssBox}, double, double)"/> gives it.
    /// </summary>
    internal static double? TopFloor(CssBox floatBox)
    {
        var block = floatBox.ContainingBlock;
        double contentLeft = block.Location.X + block.ActualPaddingLeft + block.ActualBorderLeftWidth;
        double contentRight = block.ClientLeft + block.AvailableWidth;

        return TopFloor(floatBox, CssBoxHelper.CollectPrecedingFloatsInBfc(floatBox), contentLeft, contentRight);
    }

    /// <summary>
    /// Whether any of <paramref name="floats"/> would be placed elsewhere from where the content
    /// before it is in its block's current lines than from where that content was when it was
    /// placed: the lines laid out beside the floats can move a float's content to another line.
    /// </summary>
    internal static bool AnyMoved(IReadOnlyList<CssBox> floats)
    {
        foreach (var floatBox in floats)
        {
            double? floor = TopFloor(floatBox);

            if (floor.HasValue != floatBox.InlineFloatTopFloor.HasValue
                || (floor is double now && floatBox.InlineFloatTopFloor is double placed && Math.Abs(now - placed) > 0.01))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Whether <paramref name="floatBox"/> is among <paramref name="block"/>'s inline content: its
    /// child, or inside inline boxes that are.
    /// </summary>
    private static bool IsInInlineContentOf(CssBox floatBox, CssBox block)
    {
        for (var parent = floatBox.ParentBox; parent != null; parent = parent.ParentBox)
        {
            if (parent == block)
                return true;

            if (!IsInlineBox(parent))
                return false;
        }

        return false;
    }
}
