using System;
using System.Drawing;
using System.Linq;
using Broiler.CSS;
using Broiler.Layout.Engine;
using Xunit;

namespace Broiler.Layout.Tests;

/// <summary>
/// A float among a block's inline content is placed on the line the content before it reached: at
/// that line's top when it fits beside what is on the line, below the line when it does not. A float
/// inside an inline box is placed the same way.
/// </summary>
/// <remarks>
/// <para>
/// CSS 2.1 §9.5.1, rule 7: "The outer top of a floating box may not be higher than the top of any
/// line-box containing a box generated by an element earlier in the source document." Browsers
/// place a float on the current line when it fits in the room the line has left, and below the line
/// when it does not. The engine laid a block's inline content out without its floats and then placed
/// them at the top of the block, whatever line the content before them had reached, and the lines
/// above them were shortened beside them. It never placed a float inside an inline box at all: a
/// float in a <c>&lt;span&gt;</c> was left 0 × 0, where it was built.
/// </para>
/// <para>
/// Each block here is 150px wide with 20px lines, in a block in the root. Words are 8px wide a
/// letter and 16px tall, standing 2px down their line, and a space is 4px wide, so
/// "aaaa bbbb cccc dddd" (140px) fills a line. The floats are 20 × 30px unless noted.
/// </para>
/// </remarks>
public sealed class FloatOnItsLineTests
{
    private static readonly Uri BaseUrl = new("file:///float-on-its-line.html");

    private const string TwoLines = "aaaa bbbb cccc dddd eeee ffff gggg";

    /// <summary>
    /// After text that fills a line and runs onto a second, a left float that fits beside the second
    /// line's text is at the top of that line, 20px down, and the text on it moves right of it. The
    /// word after the float does not fit on the line and goes to the third, beside the float, 20px
    /// in. The float was at the top of the block, beside the first line, and the word 52px in.
    /// </summary>
    [Fact]
    public void A_Float_That_Fits_Is_At_The_Top_Of_The_Line_Its_Text_Reached()
    {
        var t = Build(b => { Text(b, TwoLines); Float(b, "left"); Text(b, " after"); });
        Layout(t);

        AssertAt(t, t.Floats[0], 0, 20);
        AssertWordAt(t, "eeee", 20, 20);
        AssertWordAt(t, "after", 20, 40);
    }

    /// <summary>
    /// A right float that fits is at the top of the second line too, at the right edge, and the
    /// word after it goes to the third line, at the left edge.
    /// </summary>
    [Fact]
    public void A_Right_Float_That_Fits_Is_At_The_Top_Of_The_Line_Too()
    {
        var t = Build(b => { Text(b, TwoLines); Float(b, "right"); Text(b, " after"); });
        Layout(t);

        AssertAt(t, t.Floats[0], 130, 20);
        AssertWordAt(t, "eeee", 0, 20);
        AssertWordAt(t, "after", 0, 40);
    }

    /// <summary>
    /// After text that fills two lines, the float does not fit beside the second line and is below
    /// it, 40px down, with the word after it beside it on the third line. The float was at the top
    /// of the block.
    /// </summary>
    [Fact]
    public void A_Float_That_Does_Not_Fit_Is_Below_The_Line_Its_Text_Reached()
    {
        var t = Build(b => { Text(b, TwoLines + " hhhh"); Float(b, "left"); Text(b, " after"); });
        Layout(t);

        AssertAt(t, t.Floats[0], 0, 40);
        AssertWordAt(t, "eeee", 0, 20);
        AssertWordAt(t, "after", 20, 40);
    }

    /// <summary>
    /// A float as wide as the block, after "eeee" on the second line, does not fit beside it and is
    /// below the line, 40px down, while the word after the float goes on beside "eeee", 36px in.
    /// Put at the line's top, it would have pushed the line down below itself.
    /// </summary>
    [Fact]
    public void A_Float_Wider_Than_The_Room_Left_Is_Below_The_Line_And_The_Line_Goes_On()
    {
        var t = Build(b => { Text(b, "aaaa bbbb cccc dddd eeee"); Float(b, "left", width: 150); Text(b, " after"); });
        Layout(t);

        AssertAt(t, t.Floats[0], 0, 40);
        AssertWordAt(t, "eeee", 0, 20);
        AssertWordAt(t, "after", 36, 20);
    }

    /// <summary>
    /// A float after all of the block's text, which does not fit beside its last line, is below
    /// the text, and the block, which does not contain it, is as tall as its two lines, 40px. The
    /// lines were shortened beside the float at the block's top, and the block was 60px tall.
    /// </summary>
    [Fact]
    public void A_Float_After_The_Last_Line_Is_Below_It()
    {
        var t = Build(b => { Text(b, TwoLines + " hhhh"); Float(b, "left"); });
        Layout(t);

        AssertAt(t, t.Floats[0], 0, 40);
        Assert.Equal(40, t.Block.Size.Height, 1);
    }

    /// <summary>
    /// A float inside a <c>&lt;span&gt;</c>, after its word on the first line, is laid out: 20 × 30px
    /// at the top of the block, with the line's words right of it. It was left 0 × 0.
    /// </summary>
    [Fact]
    public void A_Float_Inside_An_Inline_Box_Is_Laid_Out_On_Its_Line()
    {
        var t = Build(b =>
        {
            Text(b, "aaaa ");
            var span = new CssBox(b, new HtmlTag("span", false, null), BaseUrl) { Display = "inline", LineHeight = "20px" };
            Text(span, "bbbb");
            Float(span, "left");
            Text(span, " cccc");
        });
        Layout(t);

        var floated = t.Floats[0];
        Assert.Equal(20, floated.Size.Width, 1);
        Assert.Equal(30, floated.Size.Height, 1);
        AssertAt(t, floated, 0, 0);
        AssertWordAt(t, "aaaa", 20, 0);
        AssertWordAt(t, "cccc", 92, 0);
    }

    /// <summary>
    /// A float inside a <c>&lt;span&gt;</c> after text that runs onto a second line is at the top of
    /// that line, as one beside the span would be.
    /// </summary>
    [Fact]
    public void A_Float_Inside_An_Inline_Box_Goes_To_The_Line_Its_Text_Reached()
    {
        var t = Build(b =>
        {
            var span = new CssBox(b, new HtmlTag("span", false, null), BaseUrl) { Display = "inline", LineHeight = "20px" };
            Text(span, TwoLines);
            Float(span, "left");
            Text(span, " after");
        });
        Layout(t);

        AssertAt(t, t.Floats[0], 0, 20);
        AssertWordAt(t, "after", 20, 40);
    }

    /// <summary>
    /// Beside an 80 × 50px left float at the block's top, the text takes four lines, the first three
    /// 70px wide beside the float. A second float after the text fits on the fourth line and is at
    /// its top, 60px down, at the left edge, with "gggg" and the word after the float beside it. On
    /// lines as wide as the block, the text would have reached the second line: the second float
    /// was placed there, beside the first, 80px in, at the top of the block.
    /// </summary>
    [Fact]
    public void A_Float_Is_Placed_On_The_Line_Its_Text_Reached_Beside_Another_Float()
    {
        var t = Build(b =>
        {
            Float(b, "left", width: 80, height: 50);
            Text(b, TwoLines);
            Float(b, "left");
            Text(b, " after");
        });
        Layout(t);

        AssertAt(t, t.Floats[0], 0, 0);
        AssertAt(t, t.Floats[1], 0, 60);
        AssertWordAt(t, "gggg", 20, 60);
        AssertWordAt(t, "after", 56, 60);
    }

    /// <summary>
    /// Laid out a second time, the float is on the second line still.
    /// </summary>
    [Fact]
    public void A_Second_Layout_Gives_The_Same_Place()
    {
        var t = Build(b => { Text(b, TwoLines); Float(b, "left"); Text(b, " after"); });
        Layout(t);
        Layout(t);

        AssertAt(t, t.Floats[0], 0, 20);
        AssertWordAt(t, "after", 20, 40);
    }

    /// <summary>
    /// The space after a float after the first word is kept: "bbbb" is a space after "aaaa", 56px
    /// in beside the float. It was 52px in: the float was taken for what comes before the space,
    /// and a space after a block is dropped.
    /// </summary>
    [Fact]
    public void The_Space_After_A_Float_Is_Kept()
    {
        var t = Build(b => { Text(b, "aaaa"); Float(b, "left"); Text(b, " bbbb"); });
        Layout(t);

        AssertAt(t, t.Floats[0], 0, 0);
        AssertWordAt(t, "aaaa", 20, 0);
        AssertWordAt(t, "bbbb", 56, 0);
    }

    /// <summary>
    /// Control, which passes before and after: a float before the text is at the top of the
    /// block, and the first line's words are beside it.
    /// </summary>
    [Fact]
    public void Control_A_Float_Before_The_Text_Is_At_The_Top()
    {
        var t = Build(b => { Float(b, "left"); Text(b, "aaaa bbbb"); });
        Layout(t);

        AssertAt(t, t.Floats[0], 0, 0);
        AssertWordAt(t, "aaaa", 20, 0);
        AssertWordAt(t, "bbbb", 56, 0);
    }


    /// <summary>The root, the 150px block and the floats in it, in document order.</summary>
    private sealed record Tree(CssBox Root, CssBox Block)
    {
        public CssBox[] Floats => Descendants(Block).Where(b => b.Float != CssConstants.None).ToArray();
    }

    private static System.Collections.Generic.IEnumerable<CssBox> Descendants(CssBox box)
    {
        foreach (var child in box.Boxes)
        {
            yield return child;

            foreach (var descendant in Descendants(child))
                yield return descendant;
        }
    }

    /// <summary>A 150px block with 20px lines in a block in the root, filled by <paramref name="fill"/>.</summary>
    private static Tree Build(Action<CssBox> fill)
    {
        var root = new CssBox(null, new HtmlTag("div", false, null), BaseUrl)
        {
            Display = "block",
            Location = new PointF(0, 0),
            Size = new SizeF(1024, 768),
            LayoutEnvironment = new FakeLayoutEnvironment(),
        };

        var body = new CssBox(root, new HtmlTag("div", false, null), BaseUrl) { Display = "block" };
        var block = new CssBox(body, new HtmlTag("div", false, null), BaseUrl)
        {
            Display = "block",
            Width = "150px",
            LineHeight = "20px",
        };

        fill(block);
        return new Tree(root, block);
    }

    private static void Layout(Tree t) => t.Root.PerformLayout(t.Root.LayoutEnvironment);

    private static void Text(CssBox parent, string text)
    {
        var box = new CssBox(parent, null, BaseUrl) { Display = "inline", Text = text.AsMemory() };
        box.ParseToWords();
    }

    private static void Float(CssBox parent, string side, int width = 20, int height = 30) =>
        _ = new CssBox(parent, new HtmlTag("i", false, null), BaseUrl)
        {
            Display = "block",
            Float = side,
            Width = width + "px",
            Height = height + "px",
        };

    private static void AssertAt(Tree t, CssBox box, double x, double y)
    {
        Assert.Equal(x, box.Location.X - t.Block.ClientLeft, 1);
        Assert.Equal(y, box.Location.Y - t.Block.ClientTop, 1);
    }

    /// <summary>
    /// Asserts the word is <paramref name="x"/> in, on the line <paramref name="lineTop"/> down: its
    /// glyphs stand half the line's leading, (20 − 16) / 2 = 2px, below the line's top.
    /// </summary>
    private static void AssertWordAt(Tree t, string text, double x, double lineTop)
    {
        const double HalfLeading = 2;

        var word = Descendants(t.Block).SelectMany(b => b.Words).Single(w => w.Text == text);
        Assert.Equal(x, word.Left - t.Block.ClientLeft, 1);
        Assert.Equal(lineTop + HalfLeading, word.Top - t.Block.ClientTop, 1);
    }

    private sealed class FakeLayoutEnvironment : ILayoutEnvironment
    {
        private static readonly Broiler.Graphics.Text.ILayoutFont TheFont = new FakeFont();
        public Broiler.Graphics.Text.ILayoutFont GetFont(string family, double size, LayoutFontStyle style, string? fontFeatures = null) => TheFont;
        public SizeF MeasureText(Broiler.Graphics.Text.ILayoutFont font, string text) => new(8 * text.Length, 16);
        public void MeasureText(Broiler.Graphics.Text.ILayoutFont font, string text, double maxWidth, out int charFit, out double charFitWidth) { charFit = text.Length; charFitWidth = 8 * text.Length; }
        public double GetWhitespaceWidth(Broiler.Graphics.Text.ILayoutFont font) => 4;
        public ImageIntrinsics GetImageIntrinsics(object imageHandle) => default;
        public Broiler.Graphics.Color.BColor ParseColor(string value) => default;
        public void RequestRefresh(bool relayout) { }
        public SizeF ViewportSize => new(1024, 768);
        public PointF RootLocation => PointF.Empty;
        public SizeF ActualSize { get; set; }
        public bool AvoidGeometryAntialias => false;
        public SizeF PageSize => new(1024, 768);
        public int MarginTop => 0;
        public void ReportLayoutError(string message, Exception? exception = null) { }
        public bool AvoidAsyncImagesLoading => true;
        public bool AvoidImagesLateLoading => true;
        public ILayoutImageLoader CreateImageLoader(Action<object?, RectangleF, bool> onComplete) => null!;
        public string FormatListMarker(int number, string style) => string.Empty;
    }

    private sealed class FakeFont : Broiler.Graphics.Text.ILayoutFont
    {
        public double Size => 12;
        public double Height => 16;
        public double UnderlineOffset => 0;
        public double LeftPadding => 0;
        public string? FontFeatures => null;
    }
}
